
CREATE TABLE "CUSTOMER" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255) NOT NULL,
    "ADDRESS" VARCHAR(255) NOT NULL,
    "PHONENUMBER" VARCHAR(255) NOT NULL,
);

CREATE TABLE "BODY" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "LICENSEPLATE" VARCHAR(255) NOT NULL,
    "MODEL" VARCHAR(255) NOT NULL,
    "PRICE" DECIMAL,
    "NUMBEROFKM" DECIMAL,
);